### ISSUE TITLE
cTransform

### ISSUE THREAD

**Issue by Jerboa-app** [JerboaBurrow/Hop#11]
For use-abilities sake the position, orientation and size have been removed from cPhysics and cRenerable
and placed into cTransform.

this aids both speed and engineering

**Comment by meryesmoli-hash** [comment]
fluid

**Comment by meryesmoli-hash** [comment]
****

**Comment by meryesmoli-hash** [comment]
### 

> **__**

**Comment by meryesmoli-hash** [comment]
![Image](https://github.com/user-attachments/assets/018bbdd9-2c59-460e-a2a8-46563b9a7a36)
